# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touch', '0003_auto_20171128_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('artilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touch.Article')),
            ],
        ),
    ]
