# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touch', '0005_auto_20171128_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '活动资讯', 'verbose_name_plural': '活动资讯'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品中心', 'verbose_name_plural': '产品中心'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '常见问题', 'verbose_name_plural': '常见问题'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '专家团队', 'verbose_name_plural': '专家团队'},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'verbose_name': '技术培训', 'verbose_name_plural': '技术培训'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
    ]
