# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touch', '0008_auto_20171216_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('date', models.DateTimeField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章汇总',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touch.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touch.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touch.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='team',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touch.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='train',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touch.Article', verbose_name='文章'),
        ),
    ]
